#! /bin/sh

sxhkd &
$HOME/.config/polybar/launch.sh
feh --bg-scale ~/Pictures/wallapper.jpg

bspc monitor -d 1 2 3 4 5 6 7 8 9 10 eXtra

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a spotify desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a brave-browser desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify pseudo_tiled=on
bspc rule -a yad floating=on
bspc rule -a zathura floating=off
bspc rule -a Feh floating=true center=true
bspc rule -a gnome-tweaks floating=on
