---
- name: Install Oh My Zsh
  shell: >
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Install Kitty
  shell: >
    curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
  args:
    creates: ~/.local/kitty.app

- name: Create symlink for Kitty in /usr/bin
  file:
    src: ~/.local/kitty.app/bin/kitty
    dest: /usr/bin/kitty
    state: link
    force: yes

- name: Create symlink for Kitty in ~/.local/bin
  file:
    src: ~/.local/kitty.app/bin/kitty
    dest: ~/.local/bin/kitty
    state: link
    force: yes

- name: Install Cargo (Rust)
  shell: >
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  args:
    creates: ~/.cargo

- name: Update Cargo (Rust)
  shell: >
    source $HOME/.cargo/env && rustup update
  when: ansible_facts.env_vars.HOME is defined

- name: Install Yazi using cargo
  shell: >
    source $HOME/.cargo/env && cargo install --locked yazi-fm yazi-cli
  args:
    creates: $HOME/.cargo/bin/yazi
  when: ansible_facts.env_vars.HOME is defined

- name: Install NVM
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
  args:
    creates: "~/.nvm/nvm.sh"

- name: Install Node.js (lts/iron) using NVM
  shell: >
    zsh && nvm install lts/iron
  when: ansible_facts.env_vars.HOME is defined

- name: Install Yarn
  shell: >
    npm install --global yarn

- name: Install PNPM
  shell: >
    curl -fsSL https://get.pnpm.io/install.sh | sh -
  args:
    creates: "~/.local/share/pnpm"

- name: Install httpYac
  shell: >
    npm install --global httpyac

- name: Install CascadiaCode NF
  shell: >
    wget -P ~/.local/share/fonts https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip && cd ~/.local/share/fonts && unzip CascadiaCode.zip && rm CascadiaCode.zip && fc-cache -fv
