---
- name: Update apt cache and upgrade all packages
  become: true
  become_user: root
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required packages
  become: true
  become_user: root
  apt:
    name:
      - git
      - zsh
      - neovim
      - vim
      - curl
      - wget
      - zip
      - unzip
      - gcc
      - make
      - tree
      - build-essential
      - fontconfig
      - htop
      - mosh
      - fzf
      - exa
      - bat
      - iredis
      - python3
    state: present
